FROM node:14-alpine

WORKDIR /app

COPY api api
COPY package.json .
COPY redwood.toml .
COPY yarn.lock .
COPY .yarn .yarn
COPY .yarnrc.yml .yarnrc.yml

RUN yarn install
# should add this due to pre-render
RUN yarn add react react-dom
RUN yarn rw build api
RUN rm -rf ./api/src

WORKDIR /app/api

EXPOSE 8911

# this is the way, the truth and the life
ENTRYPOINT ["/bin/sh","-c", "yarn rw prisma migrate deploy; yarn rw serve api --port 8911"]
